"""
Rationale:
The demand inputs generated by this script are illustrative test instances,
not forecasts. Future demand for alternative maritime fuels such as the ones handled in the thesis is highly uncertain, 
depending on policy, technology, prices,
and fleet turnover. Making reliable long-term predictions infeasible
within the scope of this thesis.

Instead, demand profiles are created programmatically using simple, transparent
assumptions:

- Fuel switching:
  • FAME, Methanol and Ammonia demand is assumed to increase gradually over time.
  • Fossil fuels such as MGO are assumed to decline.
  • Electricity demand is kept at a moderate, stable level.

- Growth across planning periods:
  Total demand grows or declines according to these assumptions.

- Intra-period distribution:
  Within each planning period, total demand is unevenly distributed across
  operational steps (τ). This illustrates short-term fluctuations, without being overly complex.

- Reproducibility:
  The script outputs Excel sheets directly in the format required by the model.
  This makes it easy to adjust growth rates, add fuels, or create new test cases.

In summary, these demand files are illustrative scenarios designed to stress-test
the optimization model under different assumptions about fuel uptake and decline.
"""


import pandas as pd
import numpy as np

ports = ["Hub", "Sat1", "Sat2"]
fuels = ["MGO", "LNG", "FAME", "Methanol", "Ammonia"]


baseline_day = {
    "Hub":  {"MGO":  60000, "LNG":  25000, "FAME": 22000,
             "Methanol": 11000, "Ammonia":  6500},
    "Sat1": {"MGO":   9000, "LNG":   6000, "FAME":  5000,
             "Methanol": 2500, "Ammonia": 1500},
    "Sat2": {"MGO":   6000, "LNG":   4200, "FAME":  3500,
             "Methanol": 1800, "Ammonia": 1000},
}


# strategic periods (five‑year blocks 2025‑…‑2045 → t = 0 … 4)
years = [2025, 2030, 2035, 2040, 2045]   
n_t = len(years)

# Port‑specific intra‑day load profiles (8×2‑h fractions, sum = 1 for each port)
slot_share_port = {
    "Hub":  np.array([0.02, 0.05, 0.10, 0.26, 0.26, 0.18, 0.09, 0.04]),
    "Sat1": np.array([0.03, 0.06, 0.12, 0.25, 0.24, 0.16, 0.10, 0.04]),
    "Sat2": np.array([0.01, 0.04, 0.08, 0.24, 0.28, 0.20, 0.10, 0.05]),
}

# second week multiplier inside each t
week2_multiplier = {"MGO": 0.90, "LNG": 0.90,
                    "FAME": 1.10, "Methanol": 1.10, "Ammonia": 1.10}

# Port‑specific growth / decline multipliers applied each five‑year period (from 2030)
t_growth_port = {
    "Hub":  {"MGO": 0.80, "LNG": 0.95,
             "FAME": 1.20, "Methanol": 1.25, "Ammonia": 1.30},
    "Sat1": {"MGO": 0.85, "LNG": 1.00,
             "FAME": 1.15, "Methanol": 1.20, "Ammonia": 1.25},
    "Sat2": {"MGO": 0.90, "LNG": 1.05,
             "FAME": 1.10, "Methanol": 1.15, "Ammonia": 1.20},
}


def week_slots(day_dict, slot_vec, mult=1.0):
    """Return dict fuel -> vector(56) of 2‑h demand for one week."""
    out = {}
    for f, daily in day_dict.items():
        out[f] = np.tile(daily * mult * slot_vec, 7)
    return out


writer = pd.ExcelWriter("port_fuel_demand_full.xlsx", engine="xlsxwriter")

for fuel in fuels:
    rows = []  
    for port in ports:
        slot_vec = slot_share_port[port]
        # --- start with baseline (appears in 2030) ---
        current_day = baseline_day[port].copy()

        for t_idx, year in enumerate(years):
            # t = 0 (2025) gets zero demand by definition
            if t_idx == 0:
                current_day_zero = {f: 0.0 for f in fuels}
                wk1 = week_slots(current_day_zero, slot_vec)
                wk2 = week_slots(current_day_zero, slot_vec)
            else:
                wk1 = week_slots(current_day, slot_vec)
                wk2 = {f: wk1[f] * week2_multiplier[f] for f in fuels}

            demand_vec = np.concatenate([wk1[fuel], wk2[fuel]])
            # --- ensure absolute zero demand in the base year (t = 0) ---
            if t_idx == 0:
                demand_vec = np.zeros_like(demand_vec)
            for tau_idx, val in enumerate(demand_vec):
                rows.append({
                    "port_id": port,
                    "fuel_id": fuel.lower(),
                    "t": t_idx,        
                    "tau": tau_idx,      
                    "demand": val
                })

            # update daily demand for next strategic period
            if t_idx >= 1:  
                growth_factors = t_growth_port[port]
                current_day = {f: current_day[f] * growth_factors[f] for f in fuels}

    # write one sheet per fuel
    df = pd.DataFrame(rows)
    df = df[["port_id", "fuel_id", "t", "tau", "demand"]]
    df.to_excel(writer, sheet_name=fuel, index=False)

# -----------------------------------------------------------------
# ADD ELECTRICITY DEMAND SHEET
# -----------------------------------------------------------------
el_baseline_day = {"Hub": 120, "Sat1": 50, "Sat2": 40}

# 2025 baseline is zero → multiplier 0.0
el_growth = [0.0,   # 2025
             1.25,  # 2030
             1.05,  # 2035
             1.05,  # 2040
             1.00]  # 2045

el_rows = []

for port in ports:
    base_day = el_baseline_day[port]

    for t_idx, g in enumerate(el_growth):
        daily = base_day * g

        wk1 = np.tile(daily * slot_share_port[port], 7)   
        wk2 = wk1 * 0.90                       
        demand_vec = np.concatenate([wk1, wk2])  
        if t_idx == 0:
            demand_vec = np.zeros_like(demand_vec)

        for tau_idx, val in enumerate(demand_vec):
            el_rows.append({
                "port_id": port,
                "fuel_id": "el",
                "t": t_idx,    
                "tau": tau_idx,
                "demand": val
            })

# Write the electricity sheet
el_df = pd.DataFrame(el_rows)
el_df = el_df[["port_id", "fuel_id", "t", "tau", "demand"]]
el_df.to_excel(writer, sheet_name="EL", index=False)

writer.close()
print("Workbook 'port_fuel_demand_full.xlsx' created.")